package admin;

import cashier.CashiersDetails;
import client.ClientsDetails;
import items.ItemsDetails;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Amer Osama
 */
public class AdminMain extends javax.swing.JFrame {
    ImageIcon uplogo =new ImageIcon (getClass().getResource("/images/uppo.jpg"));

    /**
     * Creates new form CashMain
     */
    public AdminMain() {
        initComponents();
        this.setTitle("Home");
        this.setLocationRelativeTo(null);
                this.setIconImage(uplogo.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homepanel = new javax.swing.JPanel();
        exitlb = new javax.swing.JLabel();
        deletelb = new javax.swing.JLabel();
        InvoicesDatalb = new javax.swing.JLabel();
        tareerlb = new javax.swing.JLabel();
        ItemsDatalb = new javax.swing.JLabel();
        cashiersDatalb = new javax.swing.JLabel();
        tareercenter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quick Bill");
        setBackground(new java.awt.Color(153, 0, 0));
        setUndecorated(true);

        homepanel.setBackground(new java.awt.Color(153, 0, 0));
        homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitlbMouseClicked(evt);
            }
        });
        homepanel.add(exitlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, -1));

        deletelb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        deletelb.setForeground(new java.awt.Color(255, 255, 255));
        deletelb.setText("حذف الاوردرات");
        deletelb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletelbMouseClicked(evt);
            }
        });
        homepanel.add(deletelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 30));

        InvoicesDatalb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        InvoicesDatalb.setForeground(new java.awt.Color(255, 255, 255));
        InvoicesDatalb.setText("حصر المبيعات");
        InvoicesDatalb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvoicesDatalbMouseClicked(evt);
            }
        });
        homepanel.add(InvoicesDatalb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 30));

        tareerlb.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tareerlb.setForeground(new java.awt.Color(255, 255, 255));
        tareerlb.setText("      Your  Cash ");
        tareerlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tareerlbMouseClicked(evt);
            }
        });
        homepanel.add(tareerlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 266, 90, 20));

        ItemsDatalb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        ItemsDatalb.setForeground(new java.awt.Color(255, 255, 255));
        ItemsDatalb.setText("بيانات الاصناف");
        ItemsDatalb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemsDatalbMouseClicked(evt);
            }
        });
        homepanel.add(ItemsDatalb, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 90, 30));

        cashiersDatalb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cashiersDatalb.setForeground(new java.awt.Color(255, 255, 255));
        cashiersDatalb.setText("بيانات الكاشير");
        cashiersDatalb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashiersDatalbMouseClicked(evt);
            }
        });
        homepanel.add(cashiersDatalb, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 90, 30));

        tareercenter.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tareercenter.setForeground(new java.awt.Color(255, 255, 255));
        tareercenter.setText("الشيك اليومي");
        tareercenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tareercenterMouseClicked(evt);
            }
        });
        homepanel.add(tareercenter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 30));

        jLabel1.setBackground(new java.awt.Color(49, 51, 63));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainadmin.jpg"))); // NOI18N
        jLabel1.setToolTipText(null);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 2, true));
        jLabel1.setOpaque(true);
        homepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void close(){
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    
         public Connection getConnection()
    {
        Connection con;
        try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/xmix","root","");
            return con;
        } catch(Exception e)
        {
           return null;
        }
    }
         
    void deletedata(){
         Connection connection= getConnection();
        String query1="DELETE FROM `dates`;";
        String query2="DELETE FROM `orders`;";
        Statement st;
        ResultSet rs;
        try{
            st=connection.createStatement();
            st.executeUpdate(query1);
            st.executeUpdate(query2);
                        JLabel label = new JLabel( "تم حذف جميع الاوردرات بتجاح");  
                        label.setFont(new Font("Tahoma", Font.BOLD, 14));
                        JOptionPane.showMessageDialog(null, label);
        }
            catch(Exception e)
        {
                        JLabel label = new JLabel( "لم يتم الحذف بنحاح");  
                        label.setFont(new Font("Tahoma", Font.BOLD, 14));
                        JOptionPane.showMessageDialog(null, label);
        }
        
    }
    
    
    
    
    
    
    
    
    private void exitlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitlbMouseClicked
        // TODO add your handling code here:
        
       this.dispose();
       EnterSystem e=new EnterSystem();
       e.setVisible(true);
    }//GEN-LAST:event_exitlbMouseClicked

    private void cashiersDatalbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashiersDatalbMouseClicked
        // TODO add your handling code here:
           this.setVisible(false);
      CashiersDetails cashierdata=new CashiersDetails();
      cashierdata.setVisible(true);
    }//GEN-LAST:event_cashiersDatalbMouseClicked

    private void ItemsDatalbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemsDatalbMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
     ItemsDetails item = new ItemsDetails();
     item.setVisible(true);  
    }//GEN-LAST:event_ItemsDatalbMouseClicked

    private void tareerlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareerlbMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);    
      tareer t=new tareer();
      t.setVisible(true);
    }//GEN-LAST:event_tareerlbMouseClicked

    private void InvoicesDatalbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesDatalbMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
                 InvoicesDetails invoice=new InvoicesDetails();
                 invoice.setVisible(true);
    }//GEN-LAST:event_InvoicesDatalbMouseClicked

    private void deletelbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletelbMouseClicked
        // TODO add your handling code here:
         JLabel label = new JLabel( "هل تود بالفعل حذف جميع الاوردرات");  
         label.setFont(new Font("Tahoma", Font.BOLD, 14));
          int a=JOptionPane.showConfirmDialog(null,label);  
  if(a==JOptionPane.YES_OPTION){  
    deletedata();
  }
    }//GEN-LAST:event_deletelbMouseClicked

    private void tareercenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tareercenterMouseClicked
        // TODO add your handling code here:
           this.setVisible(false);    
      tareer t=new tareer();
      t.setVisible(true);
    }//GEN-LAST:event_tareercenterMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvoicesDatalb;
    private javax.swing.JLabel ItemsDatalb;
    private javax.swing.JLabel cashiersDatalb;
    private javax.swing.JLabel deletelb;
    private javax.swing.JLabel exitlb;
    private javax.swing.JPanel homepanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tareercenter;
    private javax.swing.JLabel tareerlb;
    // End of variables declaration//GEN-END:variables
}
